### ISSUE TITLE
Unable to prepare setup

### ISSUE THREAD

**Issue by Todilo** [mgejke/hass-sectoralarm#28]
Got an error after setting configuration files. Do I need something more?

Unable to prepare setup for platform sector_alarm.alarm_control_panel: Platform not found (No module named 'homeassistant.components.alarm_control_panel.const').

Using #27

**Comment by axlthorell** [comment]
Did you add to your configuration.yaml?

```
sector_alarm:
  email: youremail@something.com
  password: *******
  alarm_id: <can be found from the url when you login to Sector Alarm, inside "">
  code: <Your pin code to asm/disarm, optional>
  thermometers: false
  alarm_panel: true
  version: 'v1_1_76'
```
